### ISSUE TITLE
Select one of the frameworks among listed

### ISSUE THREAD

**Issue by red17electro** [isygames/TheClock#2]
Hey guys, 

I listed some frameworks over here:
https://github.com/isygames/TheClock/blob/master/Design/Requirements.%20Tech%20Stack%20%26%20Tools.md

Please, read carefully and let's try to select one of the ones listed.

**Comment by red17electro** [comment]
Feel free to add additional options, in case they are better than the ones I provided.

**Comment by john-jerome** [comment]
What about Unity?

**Comment by red17electro** [comment]
> What about Unity?

If we are going to use Unity, then we will have to develop the product in C#, which might slow down the implementation, as we do not have that much experience with it. I'd say, for now, it is better to concentrate on our strengths, and select the framework based on that.

That's why the frameworks I listed are mostly based on JavaScript: not only I already have experience with it, but it is also much easier to learn for someone else, even if it is new for the person. 

But we can still argue about that, for sure. At least while we are waiting for @Babiole77 to complete the specification of gameplay.
